=== leesbian/Magento/schemas/productsPost-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "custom_design" : {
      "type" : "string" ,
      "required" : false
    } ,
    "custom_design_from" : {
      "type" : "string" ,
      "required" : false
    } ,
    "custom_design_to" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "gift_message_available" : {
      "type" : "number" ,
      "required" : false
    } ,
    "meta_description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "meta_keyword" : {
      "type" : "string" ,
      "required" : false
    } ,
    "meta_title" : {
      "type" : "string" ,
      "required" : false
    } ,
    "msrp" : {
      "type" : "number" ,
      "required" : false
    } ,
    "msrp_display_actual_price_type" : {
      "type" : "number" ,
      "required" : false
    } ,
    "msrp_enabled" : {
      "type" : "number" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "news_from_date" : {
      "type" : "string" ,
      "required" : false
    } ,
    "news_to_date" : {
      "type" : "string" ,
      "required" : false
    } ,
    "options_container" : {
      "type" : "string" ,
      "required" : false
    } ,
    "page_layout" : {
      "type" : "string" ,
      "required" : false
    } ,
    "price" : {
      "type" : "number" ,
      "required" : false
    } ,
    "attribute_set_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "short_description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sku" : {
      "type" : "string" ,
      "required" : false
    } ,
    "special_from_date" : {
      "type" : "string" ,
      "required" : false
    } ,
    "special_price" : {
      "type" : "number" ,
      "required" : false
    } ,
    "special_to_date" : {
      "type" : "string" ,
      "required" : false
    } ,
    "status" : {
      "type" : "number" ,
      "required" : false
    } ,
    "stock_data" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "backorders" : {
          "type" : "number" ,
          "required" : false
        } ,
        "enable_qty_increments" : {
          "type" : "number" ,
          "required" : false
        } ,
        "is_in_stock" : {
          "type" : "number" ,
          "required" : false
        } ,
        "is_qty_decimal" : {
          "type" : "number" ,
          "required" : false
        } ,
        "manage_stock" : {
          "type" : "number" ,
          "required" : false
        } ,
        "max_sale_qty" : {
          "type" : "number" ,
          "required" : false
        } ,
        "min_qty" : {
          "type" : "number" ,
          "required" : false
        } ,
        "min_sale_qty" : {
          "type" : "number" ,
          "required" : false
        } ,
        "notify_stock_qty" : {
          "type" : "number" ,
          "required" : false
        } ,
        "qty" : {
          "type" : "number" ,
          "required" : false
        } ,
        "use_config_manage_stock" : {
          "type" : "number" ,
          "required" : false
        } ,
        "use_config_min_qty" : {
          "type" : "number" ,
          "required" : false
        } ,
        "use_config_min_sale_qty" : {
          "type" : "number" ,
          "required" : false
        } ,
        "use_config_max_sale_qty" : {
          "type" : "number" ,
          "required" : false
        } ,
        "use_config_backorders" : {
          "type" : "number" ,
          "required" : false
        } ,
        "use_config_enable_qty_inc" : {
          "type" : "number" ,
          "required" : false
        } ,
        "use_config_notify_stock_qty" : {
          "type" : "number" ,
          "required" : false
        }
      }
    } ,
    "tax_class_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "type_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "use_config_gift_message_available" : {
      "type" : "number" ,
      "required" : false
    } ,
    "visibility" : {
      "type" : "string" ,
      "required" : false
    } ,
    "weight" : {
      "type" : "number" ,
      "required" : false
    }
  }
}

=== leesbian/Magento/examples/productsPost-example.json
{
  "custom_design" : "default/blank" ,
  "custom_design_from" : "02/16/2012" ,
  "custom_design_to" : "05/01/2012" ,
  "description" : "Test description" ,
  "gift_message_available" : 1 ,
  "meta_description" : "Test meta" ,
  "meta_keyword" : "Test keyword" ,
  "meta_title" : "Test title" ,
  "msrp" : 11.015 ,
  "msrp_display_actual_price_type" : 1 ,
  "msrp_enabled" : 1 ,
  "name" : "Test" ,
  "news_from_date" : "02/16/2012" ,
  "news_to_date" : "16.02.2012" ,
  "options_container" : "container1" ,
  "page_layout" : "one_column" ,
  "price" : 25.5 ,
  "attribute_set_id" : "4" ,
  "short_description" : "Test short description" ,
  "sku" : "simple4f5490f31959f" ,
  "special_from_date" : "02/16/2012" ,
  "special_price" : 11.2 ,
  "special_to_date" : "03/17/2012" ,
  "status" : 1 ,
  "stock_data" : {
    "backorders" : 1 ,
    "enable_qty_increments" : 0 ,
    "is_in_stock" : 0 ,
    "is_qty_decimal" : 0 ,
    "manage_stock" : 1 ,
    "max_sale_qty" : 1 ,
    "min_qty" : 1.56 ,
    "min_sale_qty" : 1 ,
    "notify_stock_qty" : -50.99 ,
    "qty" : 1 ,
    "use_config_manage_stock" : 1 ,
    "use_config_min_qty" : 1 ,
    "use_config_min_sale_qty" : 1 ,
    "use_config_max_sale_qty" : 1 ,
    "use_config_backorders" : 1 ,
    "use_config_enable_qty_inc" : 1 ,
    "use_config_notify_stock_qty" : 1
  } ,
  "tax_class_id" : "2" ,
  "type_id" : "simple" ,
  "use_config_gift_message_available" : 0 ,
  "visibility" : "4" ,
  "weight" : 125
}
