=== leesbian/Magento/schemas/productPut-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "attribute_set_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "type_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "sku" : {
      "type" : "string" ,
      "required" : false
    } ,
    "name" : {
      "type" : "string" ,
      "required" : false
    } ,
    "meta_title" : {
      "type" : "string" ,
      "required" : false
    } ,
    "meta_description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "price" : {
      "type" : "string" ,
      "required" : false
    } ,
    "weight" : {
      "type" : "string" ,
      "required" : false
    } ,
    "status" : {
      "type" : "string" ,
      "required" : false
    } ,
    "visibility" : {
      "type" : "string" ,
      "required" : false
    } ,
    "enable_googlecheckout" : {
      "type" : "string" ,
      "required" : false
    } ,
    "tax_class_id" : {
      "type" : "string" ,
      "required" : false
    } ,
    "description" : {
      "type" : "string" ,
      "required" : false
    } ,
    "meta_keyword" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== leesbian/Magento/examples/productPut-example.json
{
  "attribute_set_id" : "4" ,
  "type_id" : "simple" ,
  "sku" : "wedding dress" ,
  "name" : "Dress_test" ,
  "meta_title" : "dress" ,
  "meta_description" : "a wedding dress" ,
  "price" : "2000.0000" ,
  "weight" : "0.5000" ,
  "status" : "1" ,
  "visibility" : "4" ,
  "enable_googlecheckout" : "1" ,
  "tax_class_id" : "7" ,
  "description" : "dress" ,
  "meta_keyword" : "dress, wedding"
}
